service: classify-api

provider:
  name: aws
  runtime: nodejs12.x
  region: af-south-1
  stage: ${opt:stage, 'dev'}
  profile: classifydepl
  environment:
    CLASSIFY_TABLE: ${self:custom.ClassifyTable.name}
    CLASSIFY_S3: ${self:custom.ClassifyS3.name}
  iamRoleStatements:
    - ${file(iam/ClassifyTableIAM.yml):ClassifyTableIAM}
    - ${file(iam/ClassifyS3IAM.yml):ClassifyS3IAM}

plugins:
  - serverless-offline

package:
  exclude:
    - .git/**
    - src/**
    - test/**
    - e2e/**
    - nodemon.json
    - README.md

resources:
  Resources:
    ClassifyTable: ${file(resources/ClassifyTable.yml):ClassifyTable}
    AttachmentsBucket: ${file(resources/ClassifyS3Bucket.yml):AttachmentsBucket}

functions:
  index:
    handler: dist/index.handler
    events:
    - http:
        cors: true
        path: '/'
        method: any
    - http:
        cors: true
        path: '{proxy+}'
        method: any

custom:
  ClassifyTable:
    arn: !GetAtt ClassifyTable.Arn
    name: !Ref ClassifyTable
  ClassifyS3:
    arn: !GetAtt AttachmentsBucket.Arn
    name: !Ref AttachmentsBucket
