ClassifyTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ClassifyTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: pk
        AttributeType: S
      - AttributeName: sk
        AttributeType: S
      - AttributeName: email
        AttributeType: S
      - AttributeName: compKeyLocation
        AttributeType: S
      - AttributeName: group
        AttributeType: S
      - AttributeName: compKeyType
        AttributeType: S
      - AttributeName: userId
        AttributeType: S
    KeySchema:
      - AttributeName: pk
        KeyType: HASH
      - AttributeName: sk
        KeyType: RANGE
    GlobalSecondaryIndexes:
      - IndexName: emailIdx
        KeySchema:
          - AttributeName: email
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: compKeyLocationIdx
        KeySchema:
          - AttributeName: group
            KeyType: HASH
          - AttributeName: compKeyLocation
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: compKeyTypeIdx
        KeySchema:
          - AttributeName: group
            KeyType: HASH
          - AttributeName: compKeyType
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: userContentIdx
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: compKeyType
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
